package com.example.filmorate.storage.model.type;

public enum ACTION {
    FRIEND_REQUEST,
    CANCEL_FRIEND_REQUEST,
    ACCEPT_REQUEST,
    DECLINE_REQUEST,
    RATING,
    REVIEW,
    REVIEW_FEED,
    COMMENT,

    EDIT_RATING,
    EDIT_REVIEW,
    EDIT_REVIEW_FEED,
    EDIT_COMMENT,

    BREAK_FRIENDSHIPS,
    DELETE_RATING,
    DELETE_REVIEW,
    DELETE_REVIEW_FEED,
    DELETE_COMMENT
}
